title: Personal Blog of Philipp Marcus
description: > # this means to ignore newlines until "baseurl:"
  This is the computer science blog of Philipp Marcus. Here, you'll find posts about Data Science, Machine Learning, Self-Driving Cars, Amazon Web Services (AWS) and Distributed Systems.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: nil #if your site has a twitter account, enter it here

# Author Settings
author: Dr. Philipp Marcus # add your name
author-img: philipp-marcus.jpg # add your photo
about-author: I am a computer scientist focussing on distributed and mobile systems, as well as data science. Always hungry to keep exploring. # add description
social-github: philippmarcus # add your Github handle
social-linkedin: philipp-marcus # add your Linkedin handle
social-email: marcus@cip.ifi.lmu.de # add your Email address

# Disqus
discus-identifier: philippmarcus # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
